name: "format code"

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # check out HEAD on the branch
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # format the latest commit
      - uses: purduesigbots/clang-format-action@main
        # use one of clang-format's supported styles or leave this out to use the style in your .clang-format file
        with:
          style: file

      # commit the changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🎨 apply clang-format changes
          branch: ${{ github.head_ref }}
